#.travis.yml

os:
  - linux
services:
  - docker

language: node_js
node_js:
  - "8.0"

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules

branches:
  only:
    - /.*/

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add @angular/cli

install:
  - yarn install

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run check-all
  - npm run e2e
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change
